"""
Django settings for mytheme project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_*9b2)#wcsp@i)$v2%rfj7o4%s6a_qc09+g8d*j31w6zo@@37q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'www.mytheme.com',
    'mytheme.com',
    '45.149.206.148',  # optional for testing via IP
    'localhost', 
    '127.0.0.1',            # optional for local dev
]

LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/my-profile/'


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Must be before 'django.contrib.admin'
    'simple_history',
    'crm.apps.CrmConfig',
    'reports.apps.ReportsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tinymce',
    'django.contrib.humanize',
    'widget_tweaks',
    # for live notifications by Ashutosh
    "channels",
    "notifications",
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'crm.middleware.IPRestrictionMiddleware', #TO check ip on every request
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'crm.middleware.CRMNamespacePermissionMiddleware',#first check for crm permission
    
]

ROOT_URLCONF = 'mytheme.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates/'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',# added by Ashutosh for dynamic menu
            ],
        },
    },
]

#---------- for live notifications by Ashutosh ----------------
ASGI_APPLICATION = "mytheme.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}
# ----------------------------------------------

WSGI_APPLICATION = 'mytheme.wsgi.application'

#########Jzz setting theme #######

JAZZMIN_SETTINGS = {

    "site_title": "APIS CRM Admin",
    "site_header": "Welcome to APIS CRM Portal",
    "site_brand": "APIS CRM",
    "welcome_sign": "Welcome to APIS CRM Admin Portal",
    "copyright": "APIS",
    "custom_css": "css/custom.css",
    "search_model": ["crm.Lead", "crm.Bank"],
    "show_ui_builder": True,
    #"changeform_format": "carousel",
    #"changeform_format": "collapsible",  # default across admin, if you like
    #"changeform_format_overrides": {
    #"crm.lead": "collapsible", },      # ensure Lead uses collapsible
    "sticky_actions": True,
    # Top menu links
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {"app": "crm"},
        #{"name": "Reports", "url": "/admin/crm/report/", "icon": "fas fa-chart-bar"},
        #{"name": "Bulk Lead Upload", "url": "crm_lead_upload", "icon": "fas fa-chart-bar"},
        #{"name": "HR", "icon": "fas fa-users", "model": "crm.candidateonboarding"},  # optional shortcut
    ],

    # Icons (optional)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "crm.lead": "fas fa-user-tie",
        "crm.bank": "fas fa-university",
    },

    # Change layout, themes, etc.
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],  # Hide actual reports app if it exists
    "hide_models": [
        "crm.userprofile",
        "reports.report",
        "crm.loanproduct",
        "crm.loanapplication",
        "crm.contact",
    ],

    "order_with_respect_to": [
        "auth", 
        "crm.IPRange",
        "crm.branch", #Added branch to top for easy access by Ashutosh
        "crm.bank",
        "crm.lead",
        "crm.leadfollowup",
        "crm.document",
        "crm.bankfeedback",
        # "reports",
        ],
    

    "custom_links": {
        "auth": [
            {
                "name": "User Profiles",
                "url": "/admin/crm/userprofile/",
                "icon": "fas fa-user-circle",
                "permissions": ["crm.view_userprofile"],  # or 'change', 'add', etc.
            }, 
            {
                "name": "Field Access Control",
                "url": "field_access_control",   # uses the name from urls.py
                "icon": "fas fa-lock",
                "permissions": ["crm.view_fieldaccesscontrol"],  # or 'change', 'add', etc.
            },
            
        ],

        "crm": [
                # {
                #     "name": "Upload Leads (CSV/XLSX)",
                #     "url": "crm_lead_upload",
                #     "icon": "fas fa-file-upload",
                #     "permissions": ["crm.add_lead"],
                # },
                # {
                #     "name": "Report Builder",
                #     "url": "select_report_model",  # Django URL name
                #     "icon": "fas fa-chart-line",
                # },
                # {
                #     "name": "User Tracking Report",
                #     "url": "/reports/user-activity/",
                #     "icon": "fas fa-user-clock",
                #     "permissions": ["auth.view_user"],
                # },
                {
                    "name": "Data Upload",
                    "url": "crm-data-upload",
                    "permissions": ["crm.can_export_data"],  #  uses the app_name + name defined above
                },   
            ], 
        
            # "reports": [
            #     {
            #         "name": "MTD Report",
            #         "url": "reports:mtd_reports",  # Django URL name
            #         "icon": "fas fa-chart-bar",
            #     },
            #     {
            #         "name": "MTD WIP Report",
            #         "url": "reports:mtd_wip_report",  # Django URL name
            #         "icon": "fas fa-tasks",
            #     },
            # ],
    }   
}
JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",  # You can choose any other supported theme if desired

    # Reduce padding and font sizes for a compact UI
    "body_small_text": True,               # Smaller text throughout the body
    "sidebar_nav_small_text": True,        # Smaller text in the sidebar
    "sidebar_disable_expand": False,        # Collapse items by default for compact sidebar
    "navbar_small_text": True,             # Smaller navbar text
    "footer_small_text": True,             # Smaller footer text

    "button_classes": {
        "primary": "btn-sm btn-primary",
        "secondary": "btn-sm btn-secondary",
        "info": "btn-sm btn-info",
        "warning": "btn-sm btn-warning",
        "danger": "btn-sm btn-danger",
        "success": "btn-sm btn-success",
    },

    "actions_sticky_top": True,           # Optional: prevent action buttons from sticking
}

REPORTS = {
    "MODEL_REGISTRY": "reports.registry",
    "DEFAULT_LIMIT": 5000,
    "MAX_ROWS": 20000,
}

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
"""

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'cardexperts',
        'USER': 'cardexperts_user',
        'PASSWORD': 'test@1234',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-gb'  # UK format (dd/mm/yyyy)

TIME_ZONE = 'Asia/Kolkata'
#DATE_INPUT_FORMATS = ['%d%m%Y', '%d/%m/%Y', '%d-%m-%Y']
#DATE_FORMAT = '%d/%m/%Y'
USE_I18N = True

USE_TZ = True
USE_L10N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATICFILES_DIRS = [
    BASE_DIR / 'static',  # your manually created static folder (optional)
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = '/login/'

# IP Realted
AUTHENTICATION_BACKENDS = [
    'crm.backends.IPRestrictedBackend',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
